### ISSUE TITLE
Empty SOAPAction header

### ISSUE THREAD

**Issue by veewee** [php-soap/psr18-transport#2]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     |

#### Summary

See https://github.com/phpro/soap-client/issues/398

#### Current behaviour

Soap action headers are not quoting the action.

#### Expected behaviour

Soap action headers are not quoting the action.
This also happens in ext-soap : https://github.com/php/php-src/blob/1f183792c1cf056fd45c03befbd49a60dec08bb4/ext/soap/php_http.c#L642

When this issue is fixed, we can deprecate the `QuotedSoapActionMiddleware`

**Comment by ro0NL** [comment]
IIUC quoting is generally safe as per protocol spec? But if anything, it should be opted out from in userland?

**Comment by veewee** [comment]
It should be quoted indeed:

Soap 1.1:
https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383528

Same for 1.2, but as action parameter inside the content-type tag.


In any case, that is how it works in php-src (see linked code) as well, so it should be fine to quote. I don't think you should be able to opt-out on the behavior: we rather provide correct behavior over that kind of flexibility
