### ISSUE TITLE
Add options to Guzzle Client (kerberos Auth)

### ISSUE THREAD

**Issue by prumand** [php-soap/psr18-transport#4]
|    Q        |   A
|------------ | -----
| Version     | 2.0.0

### Support Question

I need to call my SOAP-Endpoints with kerberos. But I've no clue, where I could put the options. One try was in the factory (see below). This yields an error, that the requested methods are not found.

Normally it worked, but gave me a 401. I used the wizard to generate the Code. I ran the wizard with a static XML. 

```php
public static function factory(string $wsdl) : \App\Models\Soap\InstalledItemsClient
    {
        $engine = DefaultEngineFactory::create(
            ExtSoapOptions::defaults($wsdl, [])
                ->withClassMap(InstalledItemsClassmap::getCollection()),
            new \Soap\Psr18Transport\Psr18Transport(
                new \GuzzleHttp\Client([
                    'curl' => [
                        CURLOPT_HTTPAUTH => 6,
                        CURLOPT_PASSWORD => 'user:pass'
                    ]
                ]),
                new Psr7Converter(
                    Psr17FactoryDiscovery::findRequestFactory(),
                    Psr17FactoryDiscovery::findStreamFactory()
                )
            ),
        );
```

**Comment by veewee** [comment]
Hello there,

I haven't used kerberos authentication myself.
Regarding to some articles, you can try passing following curl options to guzzle:

```
CURLOPT_GSSAPI_DELEGATION => CURLGSSAPI_DELEGATION_FLAG,
CURLOPT_HTTPAUTH => CURLAUTH_GSSNEGOTIATE, // or CURLAUTH_NEGOTIATE 
CURLOPT_USERPWD => 'user:pass',
```

Side-node: `You need to build libcurl with a suitable GSS-API library or SSPI on Windows for this to work. `

If this doesn't work, I can't help you any further on this.
However, you can log the request + response and see what is going on at HTTP level.
Maybe the SOAP server folks can help you out from that point on.

**Comment by prumand** [comment]
Thanks! Guzzle works when create the client myself with the options above, but I don't know how to instantiate Guzzle correctly with the factory or how to pass the options.

**Comment by veewee** [comment]
If it works on regular guzzle client, then it should also be used by the SoapClient.
Small question, is the provided wsdl also behind kerberos authentication? Because now you load the WSDL through phps internal wsdl loader without any authentication.
Or is it rather failing on an actual soap call?

**Comment by prumand** [comment]
I think I misplaced this question. It should have been in https://github.com/phpro/soap-client. I close it.

fyi Yes the WSDL would be behind kerberos, but here I pass a filepath. It was failing on the actual soap call.
